# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # Twig text filter Extension
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - {name: twig.extension}

    # Param converter for Doctrine MongoDB ODM
    doctrine_mongo_db_param_converter:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments: ["@doctrine_mongodb"]
        tags:
            - { name: request.param_converter, converter: doctrine.odm }
