services:
#    app.example:
#        class: Core\AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    core.app.bird_service:
        class: Core\AppBundle\Services\BirdService
        arguments: ["@service_container"]
        lazy: true
